name: hms_services
description: "A new Flutter plugin project."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.10.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter

  permission_handler: ^12.0.1

  huawei_push:
    git:
      url: https://github.com/norutplz/hms-flutter-plugin.git
      ref: hms_push_flutter_3.29
      path: flutter-hms-push
  huawei_ads:
    git:
      url: https://github.com/norutplz/hms-flutter-plugin.git
      ref: hms_push_flutter_3.29
      path: flutter-hms-ads

  logger: ^2.6.2

  hive_ce: ^2.15.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0